<?php
/**
 * @file
 * Heartbleed module.
 */

// Default reset date: April 7, 2014
define('HEARTBLEED_DEFAULT_RESET_DATE', 1396828800);

/**
 * Implements hook_menu().
 */
function heartbleed_menu() {
  $items = array();

  $items['user/heartbleed'] = array(
    'page callback' => 'heartbleed_page',
    'access arguments' => array('access content'),
  );

  $items['admin/user/heartbleed'] = array(
    'title' => 'Heartbleed',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('heartbleed_admin_form'),
    'access arguments' => array('administer users'),
  );

  return $items;
}

/**
 * Admin config form.
 */
function heartbleed_admin_form(&$form_state) {
  $form = array();

  $form['heartbleed_password_reset_date'] = array(
    '#type' => 'textfield',
    '#title' => t('Password reset date'),
    '#default_value' => variable_get('heartbleed_password_reset_date', HEARTBLEED_DEFAULT_RESET_DATE),
    '#description' =>  t('Any users that existed in the database BEFORE this date will be prompted to update their password next time they log in. Users will receive this prompt until they update their password. Look up the unix timestamp here: !here', array('!here' => l('unixtimestamp.com', 'http://unixtimestamp.com/'))),
  );

  $form['heartbleed_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Heartbleed Message'),
    '#description' => t('Message to be displayed to users'),
    '#default_value' => variable_get('heartbleed_message', t('Please reset your password. More information: !here and !here2.',
      array('!here' => l('heartbleed.com', 'http://heartbleed.com/'), '!here2' => l('dhs.gov/stopthinkconnect-heartbleed', 'http://www.dhs.gov/stopthinkconnect-heartbleed')))),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 */
function heartbleed_form_alter(&$form, &$form_state, $form_id) {
  // Hook into user login forms to add our submit handler after user module's
  // submit handler.
  if ($form_id == 'user_login' || $form_id == 'user_login_block') {
    $form['#submit'][] = 'heartbleed_login_submit';
  }

  // Alter user_pass form to display heartbleed info if we're on heartbleed
  // path. If we're not on heartbleed page (e.g. if we're on the standard
  // user/password page) do nothing.
  if ($form_id == 'user_pass') {
    $args = arg();
    $path = "{$args[0]}/{$args[1]}";
    $path = strtolower("{$args[0]}/{$args[1]}");
    if ($path == 'user/heartbleed') {
      // We're on heartbleed page. Add heartbleed info to form.
      $form['heartbleed_message'] = array(
        '#type' => 'item',
        '#title' => t('Please reset your password'),
        '#description' => variable_get('heartbleed_message'),
        '#weight' => 0,
        '#prefix' => '<div class="messages warning">',
        '#suffix' => '</div>',
      );
    }

  }

}

/**
 * Submit handler for heartbleed reset.
 *
 * Upon successful login, force logout and redirect user to /heartbleed page
 * where they will receive instructions on how to reset their password.
 */
function heartbleed_login_submit($form_id, &$form_state) {
  // Check if user needs reset.
  $force_reset = heartbleed_force_reset();
  if (!$force_reset) {
    // Nothing to do here.
    return;
  }

  // Copied from user_logout().
  global $user;
  watchdog('user', 'Session closed for %name.', array('%name' => $user->name));
  module_invoke_all('user_logout', $user);
  // Destroy the current session, and reset $user to the anonymous user.
  session_destroy();
  // Do not obey Drupal's destination if set. Otherwise user is logged out and
  // redirected and they don't know why or how to fix it.
  // Re. unset $_REQUEST v. unset $_GET: See http://drupal.stackexchange.com/a/372.
  unset($_REQUEST['destination']);
  drupal_goto('user/heartbleed');
}

/**
 * Page callback at user/heartbleed. See hook_menu above.
 *
 * This looks just like user/password, with some extra info included in the form
 * by a form_alter.
 */
function heartbleed_page() {
  module_load_include('inc', 'user', 'user.pages');
  return drupal_get_form('user_pass');
}

/**
 * Check if user needs to reset password.
 *
 * @return bool
 *   Password needs reset? True or false.
 */
function heartbleed_force_reset() {
  global $user;

  // Get password reset date.
  $password_reset_date = variable_get('heartbleed_password_reset_date', HEARTBLEED_DEFAULT_RESET_DATE);

  // Get date user's password was last modified. Since this information is only
  // tracked after Heartbleed module is enabled, $last_pass_update is 0 for all
  // users when the module is first enabled.
  $last_pass_update = heartbleed_get_last_pass_update($user->uid);

  if ($user->created > $password_reset_date) {
    // If user was created AFTER password reset date, do not force reset.
    $needs_reset = FALSE;
  }
  elseif ($last_pass_update < $password_reset_date) {
    // If user was created BEFORE reset date AND the password has not been reset
    // since the reset date, user needs to reset password.
    $needs_reset = TRUE;
  }

  return $needs_reset;
}

/**
 * Implements hook_user().
 */
function heartbleed_user($op, &$edit, &$account, $category = NULL) {
  if ($op != 'update') {
    // If user is not updating anything, our work here is done.
    return;
  }

  if (empty($edit['pass'])) {
    // If user is not updating password, our work here is done.
    return;
  }

  $uid = $account->uid;
  // Determine if user exists in heartbleed table yet.
  $query = "SELECT uid FROM {heartbleed} WHERE uid = %d";
  $result = db_result(db_query($query, $uid));
  if ($result) {
    // User already exists in table. Update.
    // @todo Consider: Arguably if the user exists in the table at all, our work
    // is done. If this module only cares about a person updating their
    // password once after it's installed, no need to keep updating every time
    // a user updates their password. For a high traffic site, this would be
    // an easy way to reduce our footprint. On the other hand, having the
    // ability to arbitrarily pick a date after which password resets get
    // forced seems like convenient, generic functionality. A site that has
    // more than one reset on more than one occasion may get good value out of
    // updating this value every time.
    $query = "UPDATE {heartbleed} SET pass_last_updated = %d WHERE uid = %d";
    $result = db_query($query, time(), $uid);
  }
  else {
    // Insert.
    $query = "INSERT INTO {heartbleed} (uid, pass_last_updated) VALUES (%d, %d)";
    $result = db_query($query,$uid, time());
  }

}


/**
 * Provide last password reset timestamp.
 *
 * @param int $uid
 *   User id.
 *
 * @return int
 *   Timestamp for when user last reset pass if availble.
 */
function heartbleed_get_last_pass_update($uid) {
  $query = 'SELECT pass_last_updated FROM {heartbleed} WHERE uid = %d';
  $pass_last_updated = db_result(db_query($query, $uid));
  // If no results, cast as integer and return 0.
  return (int) $pass_last_updated;
}

/******************************************************************************
 * Taking over user/reset below is probably too aggressive. Leaving code there
 * commented out in case it's helpful to revisit later.
 *****************************************************************************/

/**
 * Implements hook_menu_alter().
 */
/*
function heartbleed_menu_alter(&$items) {
  // Take over user reset so we can effectively log the event. There's no way
  // to tell otherwise (via hook_user_update) that the user is resetting their
  // password.
  $items['user/reset/%/%/%']['page callback'] = 'heartbleed_pass_reset';
}
// */

/**
 * Callback taking over user/reset/%/%/%.
 */
/*
function heartbleed_pass_reset($uid, $timestamp, $hashed_pass) {
  // Use logic from user.pages.inc to verify legitimate reset request.
  $users = user_load_multiple(array($uid), array('status' => '1'));
  $account = reset($users);
  if ($hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login)) {

    // It's a legitimate request. Update last_reset value in heartbleed table.
    db_query('');
  }
  // Now proceed to regular password reset page we took over from user module.
  return drupal_get_form('user_pass_reset', $uid, $timestamp, $hashed_pass);
}
// */
